# Generated by Django 3.2.13 on 2023-03-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_db_tasks_mq_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_tasks',
            name='stop',
            field=models.BooleanField(default=False),
        ),
    ]
